.github/ISSUE_TEMPLATE/Bug_report.md, .github/ISSUE_TEMPLATE/Feature_request.md, .github/ISSUE_TEMPLATE/Security_issue.md, .github/ISSUE_TEMPLATE/config.yml, .github/config.yml
=> docs: Provide issue templates

.github/workflows/ci-agent-resource-discovery.yml
Deploy Resource Discovery agent on Kind cluster
Relates to https://github.com/promitor/charts/issues/5.
=> chore: Deploy Resource Discovery agent on Kind cluster

.github/workflows/ci-agent-scraper.yml
Signed-off-by: Tom Kerkhove <kerkhove.tom@gmail.com>
Relates to https://github.com/promitor/charts/issues/6
=> test: Deploy Scraper agent on Kind cluster

docs/artifacthub-repo.yml
Provide Artifact Hub repository metadata file to become a verified publisher
=> feat: Provide Artifact Hub repository metadata file

promitor-agent-resource-discovery/Chart.yaml, promitor-agent-scraper/Chart.yaml
Align Helm Chart versions with our upcoming release
=> feat: Align Helm Chart versions with our upcoming release

promitor-agent-resource-discovery/README.md, promitor-agent-scraper/README.md
Use new Helm chart registry URL
=> docs: Use new Helm chart registry URL

.github/workflows/ci-agent-resource-discovery.yml, .github/workflows/ci-agent-scraper.yml, examples/promitor-agent-resource-discovery.config.yaml, promitor-agent-resource-discovery/Chart.yaml, promitor-agent-resource-discovery/README.md, promitor-agent-scraper/Chart.yaml, promitor-agent-scraper/README.md
Show installed Helm charts & Kubernetes resources for CI deployments.
=> ci: Show installed Helm charts & Kubernetes resources for CI deployments

promitor-agent-resource-discovery/Chart.yaml, promitor-agent-scraper/Chart.yaml
Improve Helm chart descriptions
=> fix: Improve Helm chart descriptions

examples/promitor-agent-resource-discovery.config.yaml
Provide more extensive example for Resource Discovery.
=> docs: Provide more extensive example for Resource Discovery

promitor-agent-resource-discovery/README.md, promitor-agent-resource-discovery/values.yaml, promitor-agent-scraper/README.md, promitor-agent-scraper/values.yaml
Moving container images from Docker Hub to GitHub Container Registry
=> refactor: Moving container images from Docker Hub to GitHub Container Registry

examples/promitor-agent-scraper.config.yaml
Signed-off-by: Tom Kerkhove <kerkhove.tom@gmail.com>
Fixes #
=> docs: Example configuration for Scraper agent

promitor-agent-resource-discovery/README.md, promitor-agent-resource-discovery/templates/deployment.yaml, promitor-agent-resource-discovery/values.yaml, promitor-agent-scraper/Chart.yaml, promitor-agent-scraper/README.md, promitor-agent-scraper/templates/deployment.yaml, promitor-agent-scraper/values.yaml
Hello,
i've added these options to allow pod assignments to specific nodes.
=> feat: Add nodeSelector and tolerantions option to promitor-agent-scraper

examples/promitor-agent-resource-discovery.config.yaml, examples/promitor-agent-scraper.config.yaml
Signed-off-by: Tom Kerkhove <kerkhove.tom@gmail.com>
=> chore: Re-introduce Scraper example config

promitor-agent-resource-discovery/README.md, promitor-agent-resource-discovery/values.yaml, promitor-agent-scraper/README.md, promitor-agent-scraper/values.yaml
Signed-off-by: GitHub <noreply@github.com>
Fixes #
=> chore: Change container images to our Scarf Gateway

promitor-agent-resource-discovery/README.md, promitor-agent-resource-discovery/templates/service.yaml, promitor-agent-resource-discovery/templates/servicemonitor.yaml, promitor-agent-resource-discovery/values.yaml
Provide the capability to scrape Prometheus metrics in Promitor Resource Discovery.
Fixes https://github.com/tomkerkhove/promitor/issues/1717
=> feat: Provide capability to scrape Prometheus metrics in Promitor Resource Discovery

.github/workflows/ci-agent-resource-discovery.yml, .github/workflows/ci-agent-scraper.yml
=> chore: Wait for Kubernetes workload to spin up in CI

.github/workflows/ci-agent-resource-discovery.yml, .github/workflows/ci-agent-scraper.yml, promitor-agent-scraper/README.md, promitor-agent-scraper/templates/deployment.yaml, promitor-agent-scraper/templates/serviceaccount.yaml, promitor-agent-scraper/values.yaml
Provide more Kubernetes resource info during CI and ensure that the container is running.
=> chore: Provide more Kubernetes resource info during CI 

promitor-agent-resource-discovery/README.md, promitor-agent-resource-discovery/templates/deployment.yaml, promitor-agent-resource-discovery/values.yaml, promitor-agent-scraper/Chart.yaml, promitor-agent-scraper/README.md, promitor-agent-scraper/templates/deployment.yaml, promitor-agent-scraper/values.yaml
=> feat(promitor-scraper): add extraVolumes and extraVolumeMounts

.github/workflows/ci-agent-resource-discovery.yml, .github/workflows/ci-agent-scraper.yml
Deploy agents on various Kubernetes versions to verify compatability
=> test: Deploy agents on various Kubernetes versions

.github/workflows/ci-agent-scraper.yml, config/scraper.yaml
Signed-off-by: Tom Kerkhove <kerkhove.tom@gmail.com>
Fixes #78
=> test: Provide valid configuration for Scraper agent

.github/workflows/ci-agent-resource-discovery.yml, .github/workflows/ci-agent-scraper.yml
Run Helm CI on Kubernetes v1.23
=> test: Run Helm CI on Kubernetes v1.23

.github/workflows/ci-agent-resource-discovery.yml, .github/workflows/ci-agent-scraper.yml
Provide support for manual & push to main trigger
=> ci: Provide support for manual & push to main trigger

.github/workflows/ci-agent-resource-discovery.yml, .github/workflows/ci-agent-scraper.yml
Signed-off-by: Tom Kerkhove <kerkhove.tom@gmail.com>Fixes #
=> ci: Only run on Kubernetes v1.22 or above

promitor-agent-scraper/README.md, promitor-agent-scraper/templates/prometheusrule.yaml, promitor-agent-scraper/values.yaml
=> feat: allow modifying prometheus rules interval in promitor-agent-scraper

promitor-agent-resource-discovery/README.md, promitor-agent-resource-discovery/templates/deployment.yaml, promitor-agent-resource-discovery/templates/serviceaccount.yaml, promitor-agent-resource-discovery/values.yaml
Fixes #71 . I've copied the settings from #70 and tested that everything still works.
=> feat: Add secure defaults for resource discovery agent

.github/workflows/ci-agent-resource-discovery.yml, .github/workflows/ci-agent-scraper.yml
=> ci: Use more recent Kubernetes versions

promitor-agent-scraper/README.md, promitor-agent-scraper/templates/configmap.yaml
Relates to https://github.com/tomkerkhove/promitor/issues/2209
=> feat: add Azure Monitor SDK flag
